data = `[{"id" : 1, "name" : "Srijani Banerjee"},
{"id" : 2, "name" : "debarun Das"},
{"id" : 3, "name" : "Abha Singh"},
{"id" : 4, "name" : "Vikram Roy"},
{"id" : 5, "name" : "Sourav Nayak"},
{"id" : 6, "name" : "Rupsa  Ghosh"},
{"id" : 7, "name" : "Ankita Ghosal"},
{"id" : 8, "name" : "Anuska Pal"},
{"id" : 9, "name" : "Soumi Dolui"},
{"id" : 10, "name" : "Yashu Singh"},
{"id" : 11, "name" : "Anjana chaterjee"},
{"id" : 12, "name" : "Ankit Pal"},
{"id" : 13, "name" : "Supriti Nag"},
{"id" : 14, "name" : "Sanjib kumar"},
{"id" : 15, "name" : "Disha Ghosal"}
]`;